name: CI

on:
  push:
    branches:
      - main  # ou la branche que vous utilisez

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Remplacez "3.x" par la version de Python que vous utilisez

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Si vous avez un fichier requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover tests

    - name: Run linter (exemple avec flake8)
      run: |
        pip install flake8
        flake8 .

    - name: Run the script
      run: python code.py  # Remplacez "code.py" par le nom de votre fichier Python
